# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 629)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 861, 571))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_input = QtWidgets.QLabel(self.tab)
        self.label_input.setGeometry(QtCore.QRect(100, 90, 91, 17))
        self.label_input.setObjectName("label_input")
        self.label_output = QtWidgets.QLabel(self.tab)
        self.label_output.setGeometry(QtCore.QRect(460, 90, 101, 17))
        self.label_output.setObjectName("label_output")
        self.label_datatype = QtWidgets.QLabel(self.tab)
        self.label_datatype.setGeometry(QtCore.QRect(300, 90, 101, 17))
        self.label_datatype.setObjectName("label_datatype")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 110, 621, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_input = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.text_input.setObjectName("text_input")
        self.horizontalLayout.addWidget(self.text_input)
        self.cb_type = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.cb_type.setObjectName("cb_type")
        self.horizontalLayout.addWidget(self.cb_type)
        self.text_output = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.text_output.setObjectName("text_output")
        self.horizontalLayout.addWidget(self.text_output)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 190, 623, 341))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.list_input = QtWidgets.QListView(self.horizontalLayoutWidget_2)
        self.list_input.setObjectName("list_input")
        self.horizontalLayout_2.addWidget(self.list_input)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_viewInput = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_viewInput.setObjectName("btn_viewInput")
        self.verticalLayout.addWidget(self.btn_viewInput)
        self.btn_viewoutput = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_viewoutput.setObjectName("btn_viewoutput")
        self.verticalLayout.addWidget(self.btn_viewoutput)
        self.btn_move = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_move.setObjectName("btn_move")
        self.verticalLayout.addWidget(self.btn_move)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.list_output = QtWidgets.QListView(self.horizontalLayoutWidget_2)
        self.list_output.setObjectName("list_output")
        self.horizontalLayout_2.addWidget(self.list_output)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_input.setText(_translate("MainWindow", "INPUT PATH"))
        self.label_output.setText(_translate("MainWindow", "OUTPUT PATH"))
        self.label_datatype.setText(_translate("MainWindow", "DATA TYPE"))
        self.text_input.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">C:\\Users\\willy\\A</p></body></html>"))
        self.text_output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">C:\\Users\\willy\\B</p></body></html>"))
        self.btn_viewInput.setText(_translate("MainWindow", "View Input"))
        self.btn_viewoutput.setText(_translate("MainWindow", "View Output"))
        self.btn_move.setText(_translate("MainWindow", "Move to"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
